name: Sneaky-Wheel Build/Test
on: [push]

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - run: echo "Initiating sneaky-helper build..."
            - run: |
                  $(realpath `which python3`) -m venv .venv;
                  source .venv/bin/activate;
                  python -m pip install --upgrade pip setuptools wheel;
                  pip install -e .[build,test];
                  python -m build;
            - run: echo "sneaky-helper build complete..."
            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: sneaky-helper
                  path: |
                      dist
                      !dist/**/*.md
